import argparse

from config import DEFAULT_GUIDELINE
from parsing.scripts.annotate import create_annotation
from parsing.scripts.parse import parse_pdf
from parsing.methods.config import Parsers

DEFAULT_PARSER = Parsers.default().value
arg_parser = argparse.ArgumentParser()

# Input must either be a file or directory
input_group = arg_parser.add_mutually_exclusive_group()
input_group.add_argument(
    "--file",
    "-f",
    type=str,
    default=DEFAULT_GUIDELINE,
    help=f'PDF filename without extension in `data/guidelines`. If no `file` or `dir` is specified, defaults to: "{DEFAULT_GUIDELINE}".',
)
input_group.add_argument(
    "--batch",
    "-b",
    type=str,
    help=f'For Batch Processing: Directory of the PDF guidelines in `data/guidelines`.',
)

arg_parser.add_argument(
    "--parser",
    "-p",
    type=str,
    default=DEFAULT_PARSER,
    help=f'Supported PDF parsing method. Default: "{DEFAULT_PARSER}"',
    choices=[p.value for p in Parsers],
)
arg_parser.add_argument(
    "--skip_existing",
    "-S",
    action="store_true",
    help="If set files that have been previously parsed with the specified Parser will not be parsed again."
)

# If only draw is set, you cannot request to draw after parsing
draw_group = arg_parser.add_mutually_exclusive_group()
draw_group.add_argument(
    "--draw",
    "-D",
    action="store_true",
    help="If set creates an annotated PDF file showing the bounding boxes generated by the Parser."
)
draw_group.add_argument(
    "--only_draw",
    action="store_true",
    help="If set parsing is completely skipped and only the annotated documents are created."
)

args = arg_parser.parse_args()


def interface():
    """CLI for interacting with the PDF Parsing pipeline."""
    if args.batch is not None:
        src_name = args.batch
        is_batch = True
    else:
        src_name = args.file
        is_batch = False

    parser = args.parser
    if args.only_draw:
        create_annotation(parser, src_name, is_batch=is_batch)
    else:
        should_draw = args.draw
        skip_existing = args.skip_existing
        parse_pdf(parser, src_name, is_batch=is_batch, should_draw=should_draw,
                  skip_existing=skip_existing)


if __name__ == "__main__":
    interface()
